version: '3.8'
services:
  db:
    container_name: postgres_giancarlo_webcopy
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: giancarlo_web_copy
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_giancarlo_webcopy
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"